FROM node:16-slim as stage1
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production

FROM node:16-slim
ENV NODE_ENV production
WORKDIR /app
COPY . /app
COPY --from=stage1 /app/node_modules /app/node_modules
ENV REACT_APP_BASE_URL=http://localhost:5000
EXPOSE 3000
CMD ["npm", "run", "build"]
