name: release
env:
  APP_NAMESPACE: default 
on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  build-and-publish:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: trnsprntt/internship_devops_frontend:${{ github.sha }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Invoke workflow in another repo with inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: change tag in helm charts
          repo: trnsprntt/internship_devops_infrastructure
          ref: HEAD
          token: ${{ secrets.GIT_TOKEN }}
          inputs: '{ "new_tag": "${{ github.sha }}", "tier":"frontend" }'

